# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
  create:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - gh: ubuntu-22.04
          cs: linux-x64
        - gh: windows-latest
          cs: win-x64
        - gh: macos-latest
          cs: osx-x64

    runs-on: ${{ matrix.os.gh }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --verbosity normal

    - name: Publish CLI
      run: dotnet publish SlimeVROta -c Release -r ${{ matrix.os.cs }} -o builds/cli-${{ matrix.os.cs }} -p:PublishAot=true

    - name: Upload a build artifact (CLI)
      uses: actions/upload-artifact@v4
      with:
        name: SlimeVR-OTA-${{ matrix.os.cs }}
        # A file, directory or wildcard pattern that describes what to upload
        path: builds/cli-${{ matrix.os.cs }}

    - name: Publish GUI
      run: dotnet publish SlimeVROta.Gui -c Release -r ${{ matrix.os.cs }} -o builds/gui-${{ matrix.os.cs }}

    - name: Upload a build artifact (GUI)
      uses: actions/upload-artifact@v4
      with:
        name: SlimeVR-OTA-GUI-${{ matrix.os.cs }}
        # A file, directory or wildcard pattern that describes what to upload
        path: builds/gui-${{ matrix.os.cs }}
